export let content_product = [
    {
        name: "سخان مياه كهربائي فريش Venus، سعة 50 لتر، ابيض - 500004667 ",
        current_price: `<span>3,439</span><bdi>ج.م</bdi>`,
        discount : 0,
        path_image : 'https://raw.githubusercontent.com/AhmedOrgline/raya2/main/img/pro_0.webp',
    },
    {
        name: "مجفف شعر بيبي ليس Power Dry Light 2000، بقوة 2000 وات، اسود - 5910E",
        current_price: `<span>1,699</span><bdi>ج.م</bdi>`,
        present_price : `<span>2,499</span><bdi>ج.م</bdi>`,
        discount : 32,
        path_image : 'https://raw.githubusercontent.com/AhmedOrgline/raya2/main/img/pro_01.webp',
    },
    {
        name: "ساعة سمارت سامسونج Galaxy Fit 3، مقاس 1.6 بوصة - رمادي",
        current_price: `<span>3,099</span><bdi>ج.م</bdi>`,
        present_price: `<span>3,299</span><bdi>ج.م</bdi>`,
        discount : 6,
        path_image : 'https://raw.githubusercontent.com/AhmedOrgline/raya2/main/img/pro_02.webp',
    },
    {
        name: "صانع السندويشات بلاك+ديكر، 600 واط، اسود - TS1000-B5",
        current_price: `<span>1,699</span><bdi>ج.م</bdi>`,
        present_price: `<span>1,999</span><bdi>ج.م</bdi>`,
        discount : 15,
        path_image : 'https://raw.githubusercontent.com/AhmedOrgline/raya2/main/img/pro_03.webp',
    },
    {
        name: "مفرمة لحم بوش CompactPower، بقوة 500 وات، ابيض - MFW3612A",
        current_price: `<span>3,999</span><bdi>ج.م</bdi>`,
        discount : 0,
        path_image : 'https://raw.githubusercontent.com/AhmedOrgline/raya2/main/img/pro_04.webp',
    },
    {
        name: "شنطة لافينتو بيزنس لاب توب، 15.6 بوصة، أسود - BG786",
        current_price: `<span>729</span><bdi>ج.م</bdi>`,
        present_price: `<span>802</span><bdi>ج.م</bdi>`,
        discount : 9,
        path_image : 'https://raw.githubusercontent.com/AhmedOrgline/raya2/main/img/pro_05.webp',
    },
    {
        name: "محضر طعام كينوود مالتي برو كومباكت، 1.2 لتر، 800 واط، فضي - FDP302SI",
        current_price: `<span>7,499</span><bdi>ج.م</bdi>`,
        discount : 0,
        path_image : 'https://raw.githubusercontent.com/AhmedOrgline/raya2/main/img/pro_06.webp',
    },
    {
        name: "كاتيل فيليبس ديلي كوليكشن، 1.7 لتر، 2200 واط، فضي - HD9350/90",
        current_price: `<span>2,249</span><bdi>ج.م</bdi>`,
        present_price: `<span>3,000</span><bdi>ج.م</bdi>`,
        discount : 25,
        path_image : 'https://raw.githubusercontent.com/AhmedOrgline/raya2/main/img/pro_07.webp',
    },
    {
        name: "موسع نطاق واي فاي،معزز ونقطة وصول تي بي لينك، N 300 ميجابايت/ ثانية، ابيض - TL-WA855RE",
        current_price: `<span>779</span><bdi>ج.م</bdi>`,
        present_price: `<span>1,053</span><bdi>ج.م</bdi>`,
        discount : 24,
        path_image : 'https://raw.githubusercontent.com/AhmedOrgline/raya2/main/img/pro_08.webp',
    },
    {
        name: "مروحة ستاند تورنيدو بدون ريموت كنترول، 18 بوصة، اسود - TSF-18XW",
        current_price: `<span>2,229</span><bdi>ج.م</bdi>`,
        discount : 0,
        path_image : 'https://raw.githubusercontent.com/AhmedOrgline/raya2/main/img/pro_09.webp',
    },
    {
        name: "ثلاجة بيكو، نو فروست، 367 لتر، 2 باب، اسود - RDNE430K12B",
        current_price: `<span>23,480</span><bdi>ج.م</bdi>`,
        present_price: `<span>28,180</span><bdi>ج.م</bdi>`,
        discount : 17,
        path_image : 'https://raw.githubusercontent.com/AhmedOrgline/raya2/main/img/pro_001.webp',
    },
    {
        name: "بوتجاز غاز زانوسي ديجيتال، 5 شعلة، ستانلس ستيل، 90 سم - ZCG94396XA",
        current_price: `<span>16,583</span><bdi>ج.م</bdi>`,
        present_price: `<span>19,900</span><bdi>ج.م</bdi>`,
        discount : 17,
        path_image : 'https://raw.githubusercontent.com/AhmedOrgline/raya2/main/img/pro_002.webp',
    },
];

export let content_apple = [
    {
        name : "ساعة سمارت ابل SE، شاشة 44 مللي، ازرق - MR9W12",
        current_price :`<span>18,880</span><bdi>ج.م</bdi>`,
        discount : 6, 
        /* https://raw.githubusercontent.com/AhmedOrgline/raya2/main/img/screen */
        present_price : "<span>19,990</span><bdi>ج.م</bdi>",
        path_image: "https://raw.githubusercontent.com/AhmedOrgline/raya2/main/img/apple_0.webp",
    },
    {
        name : "لاب توب ابل ماك بوك اير 15.3، بروسيسور ابل M2،  256 جيجا بايت اس اس دي، 8 جيجا رام، جرافيكس 10-كور، ماك  رمادي",
        current_price : `<span>77,770</span><bdi>ج.م</bdi>`,
        discount : 3, 
        present_price : `<span>79,990</span><bdi>ج.م</bdi>`,
        path_image: "https://raw.githubusercontent.com/AhmedOrgline/raya2/main/img/apple_01.webp",
    },
    {
        name : "لابتوب ابل ماك بوك برو، بروسيسور M2، شاشة 13 بوصة، 256 جيجا اس اس دي، 8 جيجا رام، 10-كور جي بي يو، ماك او اس، رمادي",
        current_price : `<span>69,990</span><bdi>ج.م</bdi>`,
        discount : 18, 
        present_price : `<span>85,500</span><bdi>ج.م</bdi>`,
        path_image: "https://raw.githubusercontent.com/AhmedOrgline/raya2/main/img/apple_02.webp",
    },
    {
        name : "قلم ذكى ابل الجيل الثاني لأجهزة اي باد برو، أبيض",
        current_price : `<span>8,000</span><bdi>ج.م</bdi>`,
        discount : 27, 
        present_price :`<span>11,000</span><bdi>ج.م</bdi>`,
        path_image: "https://raw.githubusercontent.com/AhmedOrgline/raya2/main/img/apple_03.webp",
    },
    {
        name : "كابل ابل Type-C الى لايتنينج، 1 متر، ابيض - MM0A3ZM/A",
        current_price :`<span>1,225</span><bdi>ج.م</bdi>`,
        discount : 0, 
        //present_price : "11,000",
        path_image: "https://raw.githubusercontent.com/AhmedOrgline/raya2/main/img/apple_04.webp",
    },
    {
        name : "ايفون ابل  13 بشريحة واحدة، 128 جيجا، 4 جيجا رام، شبكة الجيل الخامس، أخضر (ضمان دولي)",
        current_price : `<span>31,499</span><bdi>ج.م</bdi>`,
        discount : 7, 
        present_price : `<span>33,798</span><bdi>ج.م</bdi>`,
        path_image: "https://raw.githubusercontent.com/AhmedOrgline/raya2/main/img/apple_05.webp",
    },
    {
        name : "تابلت ابل ايباد 10.2، 10.2 بوصة، 64 جيجا، واي فاي، فضي",
        current_price : `<span>17,900</span><bdi>ج.م</bdi>`,
        discount : 14, 
        present_price : `<span>20,789</span><bdi>ج.م</bdi>`,
        path_image: "https://raw.githubusercontent.com/AhmedOrgline/raya2/main/img/apple_06.webp",
    },
    {
        name : "تابلت ابل ايباد برو M2، 11 بوصة، 128 جيجا، واي فاي، فضي",
        current_price : `<span>59,900</span><bdi>ج.م</bdi>`,
        discount : 9, 
        present_price : `<span>65,700</span><bdi>ج.م</bdi>`,
        path_image: "https://raw.githubusercontent.com/AhmedOrgline/raya2/main/img/apple_07.webp",
    },
    {
        name : "لابتوب ابل ماك بوك اير، بروسيسور M2، شاشة 13 بوصة، 256 جيجا اس اس دي، 8 جيجا رام، 8-كور جي بي يو، ماك او اس، ستارلايت",
        current_price : `<span>57,900</span><bdi>ج.م</bdi>`,
        discount : 9, 
        present_price : `<span>75,700</span><bdi>ج.م</bdi>`,
        path_image: "https://raw.githubusercontent.com/AhmedOrgline/raya2/main/img/apple_08.webp",
    },
    {
        name : "ايفون ابل  15 برو ماكس بشريحة اتصال واحدة، 256 جيجابايت، 8 جيجا رام، شبكة الجيل الخامس - ازرق",
        current_price : `<span>62,900</span><bdi>ج.م</bdi>`,
        discount : 4, 
        present_price : `<span>65,700</span><bdi>ج.م</bdi>`,
        path_image: "https://raw.githubusercontent.com/AhmedOrgline/raya2/main/img/apple_09.webp",
    },
    {
        name : "تابلت ابل ايباد اير 5 2022 الجيل الخامس، 10.9 بوصة، 64 جيجابايت، WIFI - اسود",
        current_price :`<span>33,900</span><bdi>ج.م</bdi>`,
        discount : 15, 
        present_price : `<span>39,700</span><bdi>ج.م</bdi>`,
        path_image: "https://raw.githubusercontent.com/AhmedOrgline/raya2/main/img/apple_001.webp",
    },
    {
        name : "تابلت ابل ايباد اير 5 2022 الجيل الخامس، 64 جيجابايت، WIFI - ازرق",
        current_price : `<span>33,900</span><bdi>ج.م</bdi>`,
        discount : 15, 
        present_price : `<span>39,700</span><bdi>ج.م</bdi>`,
        path_image: "https://raw.githubusercontent.com/AhmedOrgline/raya2/main/img/apple_002.webp",
    },
];

export let content_screen = [
    {
        name : "شاشة تلفزيون سمارت ال جي 43 بوصه LED، بدقة FHD، بريسيفر داخلي - 43LM6370PVA",
        current_price :`<span>16,213</span><bdi>ج.م</bdi>`,
        discount : 10, 
        present_price : "<span>17,999</span><bdi>ج.م</bdi>",
        path_image: "https://raw.githubusercontent.com/AhmedOrgline/raya2/main/img/scren_0.webp",
    },
    {
        name : "شاشة تلفزيون تورنيدو 32 بوصه LED، بدقة HD، بريسيفر داخلي - 32EC3300E",
        current_price :`<span>8,127</span><bdi>ج.م</bdi>`,
        discount : 6, 
        present_price : "<span>8,670</span><bdi>ج.م</bdi>",
        path_image: "https://raw.githubusercontent.com/AhmedOrgline/raya2/main/img/screen_01.webp",
    },
    {
        name : "شاشة تلفزيون تورنيدو 43 بوصه DLED، بدقة FHD، بريسيفر داخلي - 43EC3300E",
        current_price :`<span>13,366</span><bdi>ج.م</bdi>`,
        discount : 1, 
        present_price : "<span>13,500</span><bdi>ج.م</bdi>",
        path_image: "https://raw.githubusercontent.com/AhmedOrgline/raya2/main/img/screen_02.webp",
    },
    {
        name : "شاشة تلفزيون سمارت سامسونج 55 بوصه QLED، بدقة 4K UHD، بريسيفر داخلي - QA55QN700C ( معاد تجديدها )",
        current_price :`<span>81,799</span><bdi>ج.م</bdi>`,
        discount : 0, 
        //present_price : "<span>13,500</span><bdi>ج.م</bdi>",
        path_image: "https://raw.githubusercontent.com/AhmedOrgline/raya2/main/img/screen_03.webp",
    },
    {
        name : "شاشة تلفزيون سمارت بلوتو 55 بوصه LED، بدقة 4K UHD، بريسيفر داخلي - PXS55UG",
        current_price :`<span>17,489</span><bdi>ج.م</bdi>`,
        discount : 8, 
        present_price : "<span>19,000</span><bdi>ج.م</bdi>",
        path_image: "https://raw.githubusercontent.com/AhmedOrgline/raya2/main/img/screen_04.webp",
    },
    {
        name : "شاشة تلفزيون سمارت جاك 43 بوصه LED، بدقة FHD، بريسيفر داخلي - 43JB821",
        current_price :`<span>13,499</span><bdi>ج.م</bdi>`,
        discount : 0, 
        //present_price : "<span>19,000</span><bdi>ج.م</bdi>",
        path_image: "https://raw.githubusercontent.com/AhmedOrgline/raya2/main/img/screen_05.webp",
    },
    {
        name : "شاشة تلفزيون سمارت تورنيدو 65 بوصه Frameless LED، بدقة 4K UHD، بريسيفر داخلي - 65UA1400E",
        current_price :`<span>25,517</span><bdi>ج.م</bdi>`,
        discount : 9, 
        present_price : "<span>27,890</span><bdi>ج.م</bdi>",
        path_image: "https://raw.githubusercontent.com/AhmedOrgline/raya2/main/img/screen_06.webp",
    },
    {
        name : "شاشة تلفزيون توشيبا 32 بوصه LED، بدقة HD، بريسيفر داخلي - 32l3965EA",
        current_price :`<span>8,500</span><bdi>ج.م</bdi>`,
        discount : 35, 
        present_price : "<span>13,000</span><bdi>ج.م</bdi>",
        path_image: "https://raw.githubusercontent.com/AhmedOrgline/raya2/main/img/screen_07.webp",
    },
    {
        name : "شاشة تلفزيون سمارت هاير 50 بوصه DLED، بدقة 4K UHD، بريسيفر داخلي - H50K62UG",
        current_price :`<span>16,000</span><bdi>ج.م</bdi>`,
        discount : 16, 
        present_price : "<span>19,000</span><bdi>ج.م</bdi>",
        path_image: "https://raw.githubusercontent.com/AhmedOrgline/raya2/main/img/screen_08.webp",
    },
    {
        name : "شاشة تلفزيون سمارت جاك 58 بوصه LED، بدقة FHD - موديل NGLD58JB631",
        current_price :`<span>16,645</span><bdi>ج.م</bdi>`,
        discount : 8, 
        present_price : "<span>18,000</span><bdi>ج.م</bdi>",
        path_image: "https://raw.githubusercontent.com/AhmedOrgline/raya2/main/img/screen_09.webp",
    },
    {
        name : "شاشة تلفزيون فريش 32 بوصه Frameless LED، بدقة HD - موديل LH324D",
        current_price :`<span>5,999</span><bdi>ج.م</bdi>`,
        discount : 14, 
        present_price : "<span>7,000</span><bdi>ج.م</bdi>",
        path_image: "https://raw.githubusercontent.com/AhmedOrgline/raya2/main/img/screen_001.webp",
    },
    {
        name : "شاشة تلفزيون سمارت أيه تي ايه 55 بوصه LED، بدقة UHD - موديل 55E4KS1",
        current_price :`<span>19,499</span><bdi>ج.م</bdi>`,
        discount : 0, 
        //present_price : "<span>7,000</span><bdi>ج.م</bdi>",
        path_image: "https://raw.githubusercontent.com/AhmedOrgline/raya2/main/img/screen_002.webp",
    },
];



